//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitacoras_pgsys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.pgsys.cl/serverwsBitacora/lista_clientes.php")]
        public string bitacoras_pgsys_lista_clientes_lista_clientes {
            get {
                return ((string)(this["bitacoras_pgsys_lista_clientes_lista_clientes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.pgsys.cl/serverwsBitacora/eliminar_cliente.php")]
        public string bitacoras_pgsys_eliminar_cliente_eliminar_cliente {
            get {
                return ((string)(this["bitacoras_pgsys_eliminar_cliente_eliminar_cliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.pgsys.cl/serverwsBitacora/crear_cliente.php")]
        public string bitacoras_pgsys_crear_cliente_crear_cliente {
            get {
                return ((string)(this["bitacoras_pgsys_crear_cliente_crear_cliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.pgsys.cl/serverwsBitacora/modificar_cliente.php")]
        public string bitacoras_pgsys_modificar_cliente_modificar_cliente {
            get {
                return ((string)(this["bitacoras_pgsys_modificar_cliente_modificar_cliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.pgsys.cl/serverwsBitacora/detalle_cliente.php")]
        public string bitacoras_pgsys_detalle_cliente_detalle_cliente {
            get {
                return ((string)(this["bitacoras_pgsys_detalle_cliente_detalle_cliente"]));
            }
        }
    }
}
