//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace bitacoras_pgsys.lista_clientes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="lista_clientesBinding", Namespace="urn:ws_mysqlBitacora")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Cliente))]
    public partial class lista_clientes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback arreglo_clientesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public lista_clientes() {
            this.Url = global::bitacoras_pgsys.Properties.Settings.Default.bitacoras_pgsys_lista_clientes_lista_clientes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event arreglo_clientesCompletedEventHandler arreglo_clientesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:pgsyswsdl#arreglo_clientes", RequestNamespace="urn:ws_mysqlBitacoras", ResponseNamespace="urn:ws_mysqlBitacoras")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Cliente[] arreglo_clientes(datos_cliente_entrada datos_cliente_entrada) {
            object[] results = this.Invoke("arreglo_clientes", new object[] {
                        datos_cliente_entrada});
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void arreglo_clientesAsync(datos_cliente_entrada datos_cliente_entrada) {
            this.arreglo_clientesAsync(datos_cliente_entrada, null);
        }
        
        /// <remarks/>
        public void arreglo_clientesAsync(datos_cliente_entrada datos_cliente_entrada, object userState) {
            if ((this.arreglo_clientesOperationCompleted == null)) {
                this.arreglo_clientesOperationCompleted = new System.Threading.SendOrPostCallback(this.Onarreglo_clientesOperationCompleted);
            }
            this.InvokeAsync("arreglo_clientes", new object[] {
                        datos_cliente_entrada}, this.arreglo_clientesOperationCompleted, userState);
        }
        
        private void Onarreglo_clientesOperationCompleted(object arg) {
            if ((this.arreglo_clientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.arreglo_clientesCompleted(this, new arreglo_clientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_mysqlBitacora")]
    public partial class datos_cliente_entrada {
        
        private string param1Field;
        
        /// <comentarios/>
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_mysqlBitacora")]
    public partial class Cliente {
        
        private string cod_datosField;
        
        private string empresa_datosField;
        
        private string titulo_datosField;
        
        private string descripcion_datosField;
        
        private string ultmod_datosField;
        
        /// <comentarios/>
        public string cod_datos {
            get {
                return this.cod_datosField;
            }
            set {
                this.cod_datosField = value;
            }
        }
        
        /// <comentarios/>
        public string empresa_datos {
            get {
                return this.empresa_datosField;
            }
            set {
                this.empresa_datosField = value;
            }
        }
        
        /// <comentarios/>
        public string titulo_datos {
            get {
                return this.titulo_datosField;
            }
            set {
                this.titulo_datosField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion_datos {
            get {
                return this.descripcion_datosField;
            }
            set {
                this.descripcion_datosField = value;
            }
        }
        
        /// <comentarios/>
        public string ultmod_datos {
            get {
                return this.ultmod_datosField;
            }
            set {
                this.ultmod_datosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void arreglo_clientesCompletedEventHandler(object sender, arreglo_clientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class arreglo_clientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal arreglo_clientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591